apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.testingservice }}
  namespace: {{ .Values.devnamespace }}
spec:
  selector:
    app: {{ .Values.testingApplicationName }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
